
mode: "train"    # "train", "infer"
run_name: ""
run_dir: "./runs/"
comment: ""    # 其他备注信息

dataset: {
  name: "",


  data_dirs: "D:/User/Desktop/train",


  cls_info: {
    others: 0,
    water: 1,
    road: 2,
    build: 3,
    land: 4,
    wood: 5,
    a: 6,
    b: 7
  },
  ignore_index: 255,
}

network: {
  type: "smp",    # "custom", ...
  arch: "Deeplabv3Plus",
  encoder: "resnet101",
  in_size: 256,
  in_channel: 3,
  out_channel: 8,
  pretrained: "imagenet",

}

optimizer: {
  type: "AdamW",
  lr: 0.0001,
#  betas: [0.9, 0.999],
  weight_decay: 0.01,
}

train: {
  epochs: 20,
  batch_size: 32,
  smoothing: 0.1,
  save_inter: -1,  # 保存间隔(epoch), 小于1表示不备份
  plot: true,
  patience: 5
}

infer: {
  ckpt_name: "best.pt",    # full path = os.path.join(run_dir, run_name, "ckpt", ckpt_name)
  in_dir: "../data/eval/refine_20220624/image/masked",
  out_dir: "eval",   # full path = os.path.join(run_dir, out_dir, "results")
  l1_win_sz: 3712,  # (512-128)*5+512=2432, (512-128)*9+512=3968, (1024-128)*3+1024=3712,
  l1_overlap: 256,
  l2_win_sz: 1024,
  l2_overlap: 128,
  batch_size: 1,
  tta: false,
  draw: false,
  evaluate: false
}

