
mode: "train"    # "train", "infer"
run_name: ""
run_dir: "./runs/"
comment: "encoder和decoder使用不同的学习率，使用Poly曲线, CELoss+FocalLoss"    # 其他备注信息


dataset: {
  "name": "S2Looking",
  "train_dirs": "../datasets/S2Looking/train",
  "val_dirs": "../datasets/S2Looking/val",
  "test_dirs": "",
  cls_info: {
    unchange: 0,
    change: 1
  },
  class_colors: {},
  ignore_index: 255,
  resample: false
}


network: {
  type: "siamese",    # "custom", ...
  arch: "FCSiamDiff",
  encoder: "resnet18",
  in_size: 512,
  in_channel: 3,
  out_channel: 2,
  pretrained: "imagenet"
}

optimizer: {
  type: "AdamW",
  lr: 0.0003,
#  betas: [0.9, 0.999],
  weight_decay: 0.01
}

train: {
  epochs: 80,
  batch_size: 8,
  smoothing: 0.1,
  save_inter: -1,  # 保存间隔(epoch), 小于1表示不备份
  log_inter: 50,   # 显示迭代间隔(batch)
  plot: true
}

eval: {
  ckpt_name: "checkpoint-final.pth",    # full path = os.path.join(run_dir, run_name, "ckpt", ckpt_name)
  test_dir: "../datasets/S2Looking/test",
  save_dir: "test_final",   # full path = os.path.join(run_dir, save_dir, "results")
  batch_size: 1,
  tta: false,
}

