
mode: "train"    # "train", "infer"
run_name: ""
run_dir: "./runs/"
comment: ""    # 其他备注信息

dataset: {
  name: "",

  data_dirs: "D:/User/Desktop/train",

  cls_info: {
#    others: 0,
#    water: 1,
#    road: 2,
#    build: 3,
#    land: 4,
#    wood: 6,
    background: 0,
    built-up: 1,
    farmland: 2,
    forest: 3,
    meadow: 4,
    water: 5
  },
  ignore_index: 255,
}

network: {
  type: "custom",    # "smp, ""custom", ...
  arch: "SegFormer",
  encoder: "mit_b3",
  in_size: 256,
  in_channel: 3,
  out_channel: 6,
  pretrained: "imagenet"
}

optimizer: {
  type: "AdamW",
  lr: 0.0001,
#  betas: [0.9, 0.999],
  weight_decay: 0.01,
}

train: {
  epochs: 20,
  batch_size: 4,
  smoothing: 0.1,
  save_inter: -1,  # 保存间隔(epoch), 小于1表示不备份
  plot: true,
  patience: 5
}

infer: {
  l1_win_sz: 2688,  # (256-128)*19+256=2688
  l1_overlap: 128,
  l2_win_sz: 256,
  l2_overlap: 128,
  batch_size: 1,
  tta: false,
}

