
mode: "train"    # "train", "infer"
run_name: ""
run_dir: "./runs/"
comment: ""    # 其他备注信息

dataset: {
  name: "",

  data_dirs: "D:/User/Desktop/RS-Seg/data/train512",


  cls_info: {
    others: 0,
    water: 1,
    road: 2,
    build: 3,
    land: 4,
    wood: 5,
  },
  ignore_index: 255,
}

network: {
  type: "custom",    # "smp, ""custom", ...
  arch: "net",
  num_classes: 6,       ##“类别数：n+1”
#  backbone: 'resnet',
  in_channel: 3,
  in_size: 512,
  pretrained: "custom",

}

optimizer: {
  type: "AdamW",
  lr: 0.0003,
#  betas: [0.9, 0.999],
  weight_decay: 0.01,
}

train: {
  epochs: 50,
  batch_size: 1,
  smoothing: 0.1,
  save_inter: -1,  # 保存间隔(epoch), 小于1表示不备份
  plot: true,
}

infer: {
  l1_win_sz: 2688,  # (256-128)*19+256=2688
  l1_overlap: 128,
  l2_win_sz: 256,
  l2_overlap: 128,
  batch_size: 1,
  tta: false,
}

