
mode: "train"    # "train", "infer"
run_name: ""
run_dir: "./runs/"
comment: ""    # 其他备注信息


dataset_params: {
  name: "",
  train_dirs: ["/home/Jiang/workspace/water/segment/data/v2/train"],
  val_dirs: ["/home/Jiang/workspace/water/segment/data/v2/val"],
  image_ext: ".tif",
  cls_info: {
    background: 0,
    water: 1
  },
  resample: false,
  ignore_index: 0
}


network_params: {
  type: "smp",    # "custom", ...
  arch: "UnetPlusPlus",
  encoder: "efficientnet-b5",
  in_height: 512,
  in_width: 512,
  in_channel: 3,
  out_channel: 2,
  pretrained: "imagenet"
}


train_params: {
  epochs: 45, # 3, 9, 21, 45, 93...
  batch_size: 4,
  lr: 0.001,
  smoothing: 0.1,
  cutmix: false,
  gamma: 0.2, # 学习率衰减系数
  momentum: 0.9,  # 动量
  weight_decay: 0.0005, # 权重衰减
  save_inter: 2,  # 保存间隔(epoch)
  min_inter: 10,    # 保存起始点(epoch)
  iter_inter: 50,   # 显示迭代间隔(batch)
  plot: true
}


inference_params: {
  ckpt_name: "checkpoint-best.pth",    # full path = os.path.join(run_dir, run_name, "ckpt", ckpt_name)
  in_dir: "/home/Jiang/workspace/gx_desheng/data/eval/tmp",
  out_dir: "test",   # full path = os.path.join(run_dir, out_dir, "results")
  l1_win_sz: 2432,  # (512-128)*5+512=2432, (512-128)*9+512=3968, (1024-128)*3+1024=3712,
  l1_overlap: 256,
  l2_win_sz: 512,
  l2_overlap: 128,
  batch_size: 4,
  tta: false,
  draw: false,
  evaluate: false
}

